image: docker:latest

services:
  - docker:dind

before_install:
  - sudo apt-get update

before_script:
  - docker info

deploy_stage:
  stage: deploy
  environment: staging
  only:
    - staging
  before_script:
  #generate ssh key
    - echo 
    - mkdir -p ~/.ssh
    - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'  
  script:
    - /bin/sh .gitlab-deploy.sh
