image: ruby:2.5

services:
  - docker:dind

before_script:
  - docker info

deploy_stage:
  stage: deploy
  environment: staging
  only:
    - staging
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y)'
  #generate ssh key
    - mkdir -p ~/.ssh
    - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    # - $SSH_PRIVATE_KEY >> memorial-backend.pem
    # - chmod 400 memorial-backend.pem
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - /bin/sh .gitlab-deploy.sh
