version: '3'
services:
  db:
    image: mysql:5.7
    environment: 
      RAILS_ENV: ${RAILS_ENV:-development}
    env_file:
      - ".${RAILS_ENV:-development}.env"
    ports:
      - "3307:3306"
    volumes:
      - 'mysql:/var/lib/mysql'
  web:
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    depends_on:
      - db
    build: .
    environment:
      MYSQL_HOST: db
      RAILS_ENV: ${RAILS_ENV:-development}
    ports:
      - "80:3000"
      - "443:3000"
    env_file:
      - ".${RAILS_ENV:-development}.env"
    volumes:
      - .:/app
volumes:
  mysql:
